### ISSUE TITLE
Training Scripts!

### ISSUE THREAD

**Issue by mksarker** [gupta-abhay/setr-pytorch#1]
Hi, 

Many thanks for your nice code.
Can you please update the Training Scripts. 
Waiting for it...!

Thanks

**Comment by 920232796** [comment]
you can look my code and train it! https://github.com/920232796/SETR-pytorch

**Comment by mksarker** [comment]
Many thanks @920232796

**Comment by gupta-abhay** [comment]
Thanks @920232796 for pointing to your training scripts. @mksarker you can please follow that or also take a look at [mmsegmentation](https://github.com/open-mmlab/mmsegmentation) which generally has test scripts for a wide variety of models.
