### ISSUE TITLE
redundant dropout at the same place

### ISSUE THREAD

**Issue by zaocan666** [gupta-abhay/setr-pytorch#3]
Line 103 in Transformer.py:
`PreNormDrop(
                            dim,
                            dropout_rate,
                            SelfAttention(
                                dim, heads=heads, dropout_rate=attn_dropout_rate
                            ),
                        )`
In the PreNormDrop module, a dropout is implemented after SelfAttention. However, in the SelfAttention module, there already exists a dropout layer at the end.
I believe PreNorm should be used instead of PreNormDrop.

**Comment by gupta-abhay** [comment]
looking at the vision transformer paper -- which is the backbone in this case -- this looks correct to me.

**Comment by zaocan666** [comment]
@gupta-abhay according to [https://github.com/rwightman/pytorch-image-models](url), maybe there is a drop_path after proj_drop in attention module. Sorry for bothering

**Comment by gupta-abhay** [comment]
sure - droppath is an extension of dropout - but for parallel paths in the network -- there are not too many in this case -- just the one residual (and I'm not too confident that we should be dropping that). you could choose to try that option -- but until I have done some testing -- does not seem like I'll be switching out to that.
