### ISSUE TITLE
model building problem

### ISSUE THREAD

**Issue by zaocan666** [gupta-abhay/setr-pytorch#4]
Hi~
I think there exists some problem in model building.
I notice that in the _decode_ function of _SETR_Naive/SETR_PUP/SETR_MLA_, some layers are initialized, like nn.Conv2d. However, the _decode_ function is in the _forward_ function of the model, so these layers will be initialized every time the model is feed data. Therefore, these layers' weight are not trained at all.
Initialization of these layers should be placed in the _init_ function of the model.

**Comment by zaocan666** [comment]
Besides, these layers should not be in a list, but in nn.Sequential or nn.ModuleList class

**Comment by gupta-abhay** [comment]
fixed. thanks.
